import type { TokenValues } from '../../templating/fill-template'
import {
  EMAIL_TYPE_PASSWORD_RESET,
  type EmailTypeDefinition
} from '../template-registry'

/**
 * The `password-reset` email type (#499, epic #497).
 *
 * `defaultSubject` / `defaultHtml` / `defaultText` below are the pre-#499 strings from
 * packages/auth/src/reset-password-email.ts, moved here CHARACTER FOR CHARACTER with the one
 * interpolation (`${url}`) turned into `{{reset_url}}`. An admin who never opens the template
 * editor therefore gets exactly the email they got before — pinned by
 * packages/core/test/email/email-registry.test.ts ("shipped defaults are byte-identical to the
 * pre-#499 output"), which fails on a one-character drift.
 */
export const PASSWORD_RESET_EMAIL: EmailTypeDefinition = {
  id: EMAIL_TYPE_PASSWORD_RESET,
  label: 'Password reset',
  description:
    'Sent to a user who asked to reset their password, or to whom an admin sent a reset link. Contains the one-time reset link.',
  tokens: [
    {
      name: 'reset_url',
      description:
        'The one-time reset link. Generated by the server for each request — a template can only place it, never change it.',
      // The value is a server-generated URL destined for an href, so it must not be
      // entity-escaped: `&` between query parameters has to stay `&`, which is also what the
      // pre-#499 string did. Nothing outside the server can influence it (better-auth builds it
      // from its own baseURL + token); the integrity test in email-registry.test.ts is the
      // kill-shot for that claim.
      rawHtml: true
    },
    {
      name: 'user_name',
      description: 'The recipient’s display name (may be empty).'
    },
    { name: 'user_email', description: 'The recipient’s email address.' },
    {
      name: 'site_title',
      description: 'Your site title, from Settings → General.'
    }
  ],
  defaultSubject: 'Reset your Setu password',
  defaultHtml: `<p>We received a request to reset the password for your Setu account.</p>
<p><a href="{{reset_url}}">Reset your password</a></p>
<p>This link will expire soon. If you didn't request this, you can safely ignore this email.</p>`,
  defaultText: `We received a request to reset the password for your Setu account.

Reset your password: {{reset_url}}

This link will expire soon. If you didn't request this, you can safely ignore this email.`,
  sampleValues: {
    reset_url:
      'https://api.example.com/api/auth/reset-password/EXAMPLE-TOKEN?callbackURL=%2Freset-password',
    user_name: 'Ada Lovelace',
    user_email: 'ada@example.com',
    site_title: 'Example Site'
  }
}

/**
 * Build the token values for one reset send. The ONLY producer of `reset_url` — the caller
 * hands over the URL better-auth generated, and no other code path can put a value under that
 * name (apps/api/src/email-templates.ts is the single call site on the server).
 */
export function passwordResetValues(input: {
  url: string
  userName?: string
  userEmail?: string
  siteTitle?: string
}): TokenValues {
  // A field the caller doesn't know is OMITTED, never set to '': an absent value lets an
  // ambient one (apps/api's live `{{site_title}}`) fill in, and renders as nothing when
  // nothing fills it, because the engine strips a token with no value either way.
  return {
    reset_url: input.url,
    ...(input.userName === undefined ? {} : { user_name: input.userName }),
    ...(input.userEmail === undefined ? {} : { user_email: input.userEmail }),
    ...(input.siteTitle === undefined ? {} : { site_title: input.siteTitle })
  }
}
