import type { BlockRegistry } from './registry'
import { markdocAttributesFor } from './markdoc-attributes'
import type { MarkdocAttr } from './markdoc-attributes'

export interface GenerateMarkdocOptions {
  /** Names of the collections declared in the resolved `setu.config` (built-ins included).
   *  Required as soon as any block has a `collectionRef()` prop — that prop's legal values
   *  ARE this list, so emitting the include without it would silently drop the check. */
  collections?: readonly string[]
}

/** One attribute's spec for the site's `blockAttr` validator
 *  (apps/site/markdoc-attr-validate.mjs). `type` is a NAME here, not the bare `String`
 *  constructor Markdoc's own type check takes: the validator owns every check so each message
 *  can name the block, the attribute and the expected values (#1126). */
function serializeAttr(
  tag: string,
  name: string,
  a: MarkdocAttr,
  collections: readonly string[] | undefined
): string {
  const bits = [`type: ${JSON.stringify(a.type)}`]
  let matches = a.matches
  if (a.ref === 'collection') {
    if (!collections)
      throw new Error(
        `generateMarkdocTagsInclude: {% ${tag} %} attribute "${name}" names a collection, ` +
          'but no declared collections were supplied'
      )
    matches = [...collections]
  }
  if (matches) bits.push(`matches: ${JSON.stringify(matches)}`)
  if (a.ref) bits.push(`ref: ${JSON.stringify(a.ref)}`)
  if (a.default !== undefined)
    bits.push(`default: ${JSON.stringify(a.default)}`)
  return `${name}: blockAttr('${tag}', '${name}', { ${bits.join(', ')} })`
}

/** Emit the source of `apps/site/markdoc.blocks.generated.mjs`. Each block's repo-root
 *  component path is rewritten relative to apps/site (`../../<path>`). Build-time only.
 *
 *  Every attribute is validated by the site's `blockAttr` and every tag by
 *  `blockTagValidate`, rather than by Markdoc's built-in `type`/`matches` checks, whose
 *  messages name the attribute but never the block (#1126). */
export function generateMarkdocTagsInclude(
  registry: BlockRegistry,
  options: GenerateMarkdocOptions = {}
): string {
  const entries = registry.blocks.map((b) => {
    const attrs = Object.entries(markdocAttributesFor(b.props)).map(
      ([name, a]) => serializeAttr(b.tag, name, a, options.collections)
    )
    // Repo-root block folders import relative to apps/site (../../). Package renderers
    // (the @setu/blocks standard renderer) are bare specifiers resolved by Vite/node —
    // emit them unchanged.
    const ref = b.component.startsWith('blocks/')
      ? `../../${b.component}`
      : b.component
    // Hyphenated tags (latest-posts) are not valid bare identifiers — quote them.
    const key = /^[A-Za-z_$][\w$]*$/.test(b.tag) ? b.tag : `'${b.tag}'`
    return (
      `  ${key}: {\n    render: component('${ref}'),\n` +
      `    attributes: { ${attrs.join(', ')} },\n` +
      `    validate: blockTagValidate('${b.tag}'),\n  },`
    )
  })
  return (
    `// AUTO-GENERATED by scripts/gen-blocks.mjs — do not edit.\n` +
    `import { component } from '@astrojs/markdoc/config'\n` +
    `import { blockAttr, blockTagValidate } from './markdoc-attr-validate.mjs'\n\n` +
    `export const tags = {\n${entries.join('\n')}\n}\n`
  )
}
