import type { BlockRegistry } from './registry'
import { markdocAttributesFor } from './markdoc-attributes'
import type { MarkdocAttr } from './markdoc-attributes'

function serializeAttrs(attrs: Record<string, MarkdocAttr>): string {
  const parts = Object.entries(attrs).map(([name, a]) => {
    const bits = [`type: ${a.type}`] // bare identifier (String/Number/Boolean) — not a string literal
    if (a.matches?.length) bits.push(`matches: ${JSON.stringify(a.matches)}`)
    if (a.default !== undefined) bits.push(`default: ${JSON.stringify(a.default)}`)
    return `${name}: { ${bits.join(', ')} }`
  })
  return `{ ${parts.join(', ')} }`
}

/** Emit the source of `apps/site/markdoc.blocks.generated.mjs`. Each block's repo-root
 *  component path is rewritten relative to apps/site (`../../<path>`). Build-time only. */
export function generateMarkdocTagsInclude(registry: BlockRegistry): string {
  const entries = registry.blocks.map((b) => {
    const attrs = serializeAttrs(markdocAttributesFor(b.props))
    return `  ${b.tag}: {\n    render: component('../../${b.component}'),\n    attributes: ${attrs},\n  },`
  })
  return (
    `// AUTO-GENERATED by scripts/gen-blocks.mjs — do not edit.\n` +
    `import { component } from '@astrojs/markdoc/config'\n\n` +
    `export const tags = {\n${entries.join('\n')}\n}\n`
  )
}
