// AUTO-GENERATED by scripts/sync-health-rubric.mjs — do not edit by hand.
// Source: https://mcp.specification.website/mcp  Synced: 2026-06-30
// To regenerate: node scripts/sync-health-rubric.mjs
// Stable ids (used by EVALUATORS/APPLIES_WHEN in checks.ts) are preserved via ID_OVERRIDES in the script.

import type { RubricItem } from './types'

export const RUBRIC: RubricItem[] = [
  // Foundations
  {
    id: 'foundations.doctype',
    category: 'foundations',
    severity: 'required',
    title: 'The HTML doctype',
    guidance:
      'Every HTML document must start with <!doctype html> as its first line. This opts the browser into standards mode; without it, you get quirks mode and broken layout.',
    url: 'https://specification.website/spec/foundations/doctype'
  },
  {
    id: 'foundations.lang',
    category: 'foundations',
    severity: 'required',
    title: 'The lang attribute on <html>',
    guidance:
      'Set a valid BCP 47 language tag on the <html> element so screen readers, translators, search engines, and browsers know what language the page is in.',
    url: 'https://specification.website/spec/foundations/html-lang'
  },
  {
    id: 'foundations.charset',
    category: 'foundations',
    severity: 'required',
    title: '<meta charset>',
    guidance:
      'Declare UTF-8 as the document character encoding in the first 1024 bytes of the HTML, so browsers parse text correctly before they hit any non-ASCII content.',
    url: 'https://specification.website/spec/foundations/meta-charset'
  },
  {
    id: 'foundations.viewport',
    category: 'foundations',
    severity: 'required',
    title: '<meta viewport>',
    guidance:
      "Tell mobile browsers to render the page at the device's actual width instead of pretending to be a 980-pixel desktop. One line, and never disable user scaling.",
    url: 'https://specification.website/spec/foundations/meta-viewport'
  },
  {
    id: 'foundations.title',
    category: 'foundations',
    severity: 'required',
    title: 'The <title> element',
    guidance:
      'Every HTML document must have exactly one non-empty <title> element inside <head>. It is used by browsers, search engines, screen readers, social previews, and AI agents.',
    url: 'https://specification.website/spec/foundations/title'
  },
  {
    id: 'foundations.description',
    category: 'foundations',
    severity: 'recommended',
    title: '<meta name="description">',
    guidance:
      'A short, unique summary of the page used by search engines and social platforms as a snippet. Google may rewrite it, but a good one is rewritten less often.',
    url: 'https://specification.website/spec/foundations/meta-description'
  },
  {
    id: 'foundations.canonical',
    category: 'foundations',
    severity: 'recommended',
    title: 'Canonical URL (rel="canonical")',
    guidance:
      'Declare the preferred URL for a page so search engines and crawlers consolidate ranking signals on one address, even when several URLs serve the same content.',
    url: 'https://specification.website/spec/foundations/canonical-url'
  },
  {
    id: 'foundations.favicon',
    category: 'foundations',
    severity: 'recommended',
    title: 'Favicons and app icons',
    guidance:
      'Ship an SVG favicon, an ICO fallback at /favicon.ico, an apple-touch-icon, and a maskable PWA icon. Five files cover every browser and home-screen surface.',
    url: 'https://specification.website/spec/foundations/favicons'
  },
  {
    id: 'foundations.theme-color',
    category: 'foundations',
    severity: 'recommended',
    title: '<meta name="theme-color">',
    guidance:
      'Tints the browser chrome and OS surfaces to match your brand. Use the media attribute to ship one colour for light mode and another for dark mode.',
    url: 'https://specification.website/spec/foundations/theme-color'
  },
  {
    id: 'foundations.color-scheme',
    category: 'foundations',
    severity: 'recommended',
    title: '<meta name="color-scheme">',
    guidance:
      'Tells the browser which colour schemes your page is designed for. Prevents the white flash that dark-mode users see before your CSS loads, and lets the browser style scrollbars, form controls, and the page background to match.',
    url: 'https://specification.website/spec/foundations/color-scheme'
  },
  {
    id: 'foundations.open-graph',
    category: 'foundations',
    severity: 'recommended',
    title: 'Open Graph protocol',
    guidance:
      'Open Graph tags control how pages look when shared on social platforms and chat apps. Set og:title, og:description, og:image, og:url, and og:type on every page.',
    url: 'https://specification.website/spec/foundations/open-graph'
  },
  {
    id: 'foundations.feed',
    category: 'foundations',
    severity: 'recommended',
    title: 'Feed discovery with rel="alternate"',
    guidance:
      'If your site publishes a feed — RSS, Atom, or JSON Feed — announce it in <head> with <link rel="alternate">. Feed readers, agents, and browsers discover it without guessing the URL.',
    url: 'https://specification.website/spec/foundations/feed-discovery'
  },
  {
    id: 'foundations.feed-hygiene',
    category: 'foundations',
    severity: 'recommended',
    title: 'Feed content hygiene',
    guidance:
      'If you publish a feed, ship it well-formed. Identify the feed inside itself with atom:link rel="self", give every item a stable guid, declare an update cadence with the Syndication module, and validate before deploy.',
    url: 'https://specification.website/spec/foundations/feed-hygiene'
  },
  {
    id: 'foundations.popover-api',
    category: 'foundations',
    severity: 'recommended',
    title: 'Popover API',
    guidance:
      'Replace ARIA-puzzled JavaScript modals, menus, and tooltips with a native top-layer primitive that the browser opens, closes, and accessibility-wires for you.',
    url: 'https://specification.website/spec/foundations/popover-api'
  },
  {
    id: 'foundations.anchor-positioning',
    category: 'foundations',
    severity: 'recommended',
    title: 'CSS anchor positioning',
    guidance:
      'Tether tooltips, menus, and popovers to the element that triggers them with pure CSS — no JavaScript positioning library, and it works across overflow and stacking boundaries.',
    url: 'https://specification.website/spec/foundations/anchor-positioning'
  },
  {
    id: 'foundations.text-wrap',
    category: 'foundations',
    severity: 'recommended',
    title: 'Balanced text wrapping',
    guidance:
      'Let the browser break headings and body copy intelligently with text-wrap: balance and pretty — no orphaned words, no manual line breaks, no layout shift.',
    url: 'https://specification.website/spec/foundations/text-wrap'
  },
  {
    id: 'foundations.container-queries',
    category: 'foundations',
    severity: 'recommended',
    title: 'CSS container queries',
    guidance:
      "Style a component by the space it is actually given with container-type and @container — responsive design that follows the container, not the viewport — and test a container's own custom properties with style queries.",
    url: 'https://specification.website/spec/foundations/container-queries'
  },
  // SEO
  {
    id: 'seo.robots-txt',
    category: 'seo',
    severity: 'recommended',
    title: 'robots.txt',
    guidance:
      'A plain-text file at the site root that tells crawlers which paths they may or may not fetch. Standardised in RFC 9309 and supported by every major search engine.',
    url: 'https://specification.website/spec/seo/robots-txt'
  },
  {
    id: 'seo.sitemap',
    category: 'seo',
    severity: 'recommended',
    title: 'XML sitemaps',
    guidance:
      'An XML file listing the canonical URLs of a site, with optional metadata about when each was last changed. The fastest way to tell a search engine what exists.',
    url: 'https://specification.website/spec/seo/xml-sitemaps'
  },
  {
    id: 'seo.sitemap-index',
    category: 'seo',
    severity: 'recommended',
    title: 'Sitemap index files',
    guidance:
      'A sitemap of sitemaps. Used when a site has more than 50,000 URLs or wants to split sitemaps by content type for cleaner reporting.',
    url: 'https://specification.website/spec/seo/sitemap-index'
  },
  {
    id: 'seo.image-sitemaps',
    category: 'seo',
    severity: 'optional',
    title: 'Image and video sitemap extensions',
    guidance:
      'Optional XML extensions that add image and video metadata to sitemap entries. Useful when media is loaded by JavaScript or hosted on a CDN that crawlers cannot reach by following links.',
    url: 'https://specification.website/spec/seo/image-sitemaps'
  },
  {
    id: 'seo.canonical-route',
    category: 'seo',
    severity: 'recommended',
    title: 'URL structure',
    guidance:
      'URLs are the most stable identifier on the web. Keep them lowercase, hyphenated, descriptive, and shallow. Treat them as a public API for your content.',
    url: 'https://specification.website/spec/seo/url-structure'
  },
  {
    id: 'seo.redirects',
    category: 'seo',
    severity: 'required',
    title: 'Redirects (301/302/308)',
    guidance:
      'HTTP redirects send a client from one URL to another. Use 301 or 308 for permanent moves, 302 or 307 for temporary ones, and never chain more than necessary.',
    url: 'https://specification.website/spec/seo/redirects'
  },
  {
    id: 'seo.server-side-rendering',
    category: 'seo',
    severity: 'recommended',
    title: 'Server-side rendering',
    guidance:
      'Crawlers, social scrapers, and AI agents index the HTML your server returns. Render your primary content and metadata server-side — via SSR, static generation, or prerendering — so it is in the initial response, not assembled later by client-side JavaScript.',
    url: 'https://specification.website/spec/seo/server-side-rendering'
  },
  {
    id: 'seo.soft-404',
    category: 'seo',
    severity: 'avoid',
    title: 'Soft 404s',
    guidance:
      "A page that looks like a 'not found' message to a user but returns 200 OK to a crawler. Search engines treat soft 404s as a quality problem and often refuse to index them.",
    url: 'https://specification.website/spec/seo/soft-404'
  },
  {
    id: 'seo.indexable',
    category: 'seo',
    severity: 'required',
    title: 'Meta robots and X-Robots-Tag',
    guidance:
      "Every page must have an explicit, correct indexing policy — either implicit (default index, follow) on public pages, or an explicit noindex / X-Robots-Tag on staging, admin, thin, or private content. Get this wrong and you either disappear from search or expose what you didn't mean to.",
    url: 'https://specification.website/spec/seo/meta-robots'
  },
  {
    id: 'seo.single-h1',
    category: 'seo',
    severity: 'required',
    title: 'Heading hierarchy',
    guidance:
      'Headings describe the sections of a page. They must form a nested outline, never be used for visual styling alone, and never skip levels.',
    url: 'https://specification.website/spec/seo/heading-hierarchy',
    needsScan: true
  },
  {
    id: 'seo.internal-linking',
    category: 'seo',
    severity: 'recommended',
    title: 'Internal linking',
    guidance:
      'Links from one page on a site to another. The strongest signal you control for telling crawlers and AI agents what a page is about and how important it is.',
    url: 'https://specification.website/spec/seo/internal-linking'
  },
  {
    id: 'seo.json-ld',
    category: 'seo',
    severity: 'recommended',
    title: 'Structured data (JSON-LD)',
    guidance:
      'Machine-readable annotations that describe the content of a page using the schema.org vocabulary. JSON-LD is the format search engines and AI agents expect.',
    url: 'https://specification.website/spec/seo/structured-data'
  },
  {
    id: 'seo.breadcrumbs',
    category: 'seo',
    severity: 'recommended',
    title: 'Breadcrumbs',
    guidance:
      "A short trail showing the page's position in the site hierarchy. Visible in the UI for users, marked up as BreadcrumbList JSON-LD for search engines.",
    url: 'https://specification.website/spec/seo/breadcrumbs'
  },
  {
    id: 'seo.indexnow',
    category: 'seo',
    severity: 'optional',
    title: 'IndexNow',
    guidance:
      'An open protocol for telling participating search engines that a URL has changed. One HTTP request pushes Bing, Yandex, Naver, and Seznam to recrawl — Google does not participate.',
    url: 'https://specification.website/spec/seo/indexnow'
  },
  // Accessibility
  {
    id: 'accessibility.color-contrast',
    category: 'accessibility',
    severity: 'required',
    title: 'Colour contrast',
    guidance:
      'Text and meaningful non-text elements must have enough contrast against their background so people with low vision and people in harsh light can read them.',
    url: 'https://specification.website/spec/accessibility/color-contrast'
  },
  {
    id: 'accessibility.forced-colors',
    category: 'accessibility',
    severity: 'recommended',
    title: 'Forced colours mode',
    guidance:
      "Respect forced colours mode (Windows High Contrast and similar). The `forced-colors` media feature lets you repair UI the user's palette would otherwise flatten — without overriding their choice.",
    url: 'https://specification.website/spec/accessibility/forced-colors'
  },
  {
    id: 'accessibility.image-alt',
    category: 'accessibility',
    severity: 'required',
    title: 'Image alt text',
    guidance:
      "Every <img> element must have an alt attribute. The value describes the image's purpose to screen readers, search engines, and anyone whose image fails to load.",
    url: 'https://specification.website/spec/accessibility/image-alt-text',
    needsScan: true
  },
  {
    id: 'accessibility.form-labels',
    category: 'accessibility',
    severity: 'required',
    title: 'Form labels',
    guidance:
      'Every form control needs a programmatically associated label. A placeholder is not a label, and an unlabelled input is unusable for screen-reader and voice-control users.',
    url: 'https://specification.website/spec/accessibility/form-labels'
  },
  {
    id: 'accessibility.keyboard-navigation',
    category: 'accessibility',
    severity: 'required',
    title: 'Keyboard navigation',
    guidance:
      'Every interactive element on the page must be reachable and operable with a keyboard alone, in a logical order, with no traps that hold focus.',
    url: 'https://specification.website/spec/accessibility/keyboard-navigation'
  },
  {
    id: 'accessibility.focus-styles',
    category: 'accessibility',
    severity: 'required',
    title: 'Visible focus indicators',
    guidance:
      'Whenever a control receives keyboard focus, the page must show a clear, high-contrast indicator. Removing focus outlines without a replacement is a top accessibility failure.',
    url: 'https://specification.website/spec/accessibility/focus-indicators'
  },
  {
    id: 'accessibility.skip-link',
    category: 'accessibility',
    severity: 'required',
    title: 'Skip links',
    guidance:
      "A 'skip to main content' link as the first focusable element lets keyboard and screen-reader users jump past repeated navigation on every page.",
    url: 'https://specification.website/spec/accessibility/skip-links'
  },
  {
    id: 'accessibility.inert-attribute',
    category: 'accessibility',
    severity: 'recommended',
    title: 'The inert attribute',
    guidance:
      'When an overlay is open, the content behind it should be unreachable — not just dimmed. The inert attribute removes a subtree from tab order and the accessibility tree at once, replacing fragile focus-trap JavaScript.',
    url: 'https://specification.website/spec/accessibility/inert-attribute'
  },
  {
    id: 'accessibility.semantic-html',
    category: 'accessibility',
    severity: 'required',
    title: 'Semantic HTML and landmarks',
    guidance:
      'Use the right HTML element for the job. Landmarks like <header>, <nav>, <main>, and <footer> let assistive technologies announce structure and skip between regions.',
    url: 'https://specification.website/spec/accessibility/semantic-html'
  },
  {
    id: 'accessibility.aria-usage',
    category: 'accessibility',
    severity: 'recommended',
    title: 'ARIA — first rule of ARIA',
    guidance:
      "ARIA can make custom widgets accessible, but the first rule of ARIA is don't use ARIA. Reach for a native HTML element first; add ARIA only when nothing native fits.",
    url: 'https://specification.website/spec/accessibility/aria-usage'
  },
  {
    id: 'accessibility.link-text',
    category: 'accessibility',
    severity: 'required',
    title: 'Descriptive link text',
    guidance:
      "Every link's text must describe where it goes. 'Click here' and 'read more' fail screen-reader users who scan a page by jumping from link to link.",
    url: 'https://specification.website/spec/accessibility/link-text'
  },
  {
    id: 'accessibility.empty-links-buttons',
    category: 'accessibility',
    severity: 'avoid',
    title: 'Empty links and buttons',
    guidance:
      'A link or button with no accessible name is invisible to screen readers and unreachable for voice control. Icon-only controls without a label are the usual culprit.',
    url: 'https://specification.website/spec/accessibility/empty-links-buttons'
  },
  {
    id: 'accessibility.form-errors',
    category: 'accessibility',
    severity: 'required',
    title: 'Accessible form errors',
    guidance:
      'When a form submission fails, errors must be identified in text, associated with the input that caused them, and announced to assistive technology.',
    url: 'https://specification.website/spec/accessibility/form-errors'
  },
  {
    id: 'accessibility.accessible-authentication',
    category: 'accessibility',
    severity: 'recommended',
    title: 'Accessible authentication',
    guidance:
      "Let people log in without solving a puzzle, transcribing a code, or memorising anything. Don't block password managers, allow paste, and offer a method that needs no cognitive function test.",
    url: 'https://specification.website/spec/accessibility/accessible-authentication'
  },
  {
    id: 'accessibility.redundant-entry',
    category: 'accessibility',
    severity: 'recommended',
    title: 'Redundant entry',
    guidance:
      "Don't make people re-type information they already gave you in the same process. Auto-populate it, or let them pick it from what they entered a step ago.",
    url: 'https://specification.website/spec/accessibility/redundant-entry'
  },
  {
    id: 'accessibility.document-language',
    category: 'accessibility',
    severity: 'required',
    title: 'Document and parts language',
    guidance:
      "Set the page's primary language on <html lang> and mark any inline content in a different language with its own lang attribute, so screen readers pronounce it correctly.",
    url: 'https://specification.website/spec/accessibility/document-language'
  },
  {
    id: 'accessibility.reduced-motion',
    category: 'accessibility',
    severity: 'required',
    title: 'Reduced motion',
    guidance:
      "Respect the user's `prefers-reduced-motion` setting. Decorative animation, parallax, and autoplay can trigger vestibular distress, migraines, and seizures.",
    url: 'https://specification.website/spec/accessibility/reduced-motion'
  },
  {
    id: 'accessibility.accessibility-overlays',
    category: 'accessibility',
    severity: 'avoid',
    title: 'Accessibility overlays',
    guidance:
      'Third-party JavaScript widgets that claim to make a site WCAG-compliant at runtime. They do not work, often harm screen-reader users, and attract lawsuits.',
    url: 'https://specification.website/spec/accessibility/accessibility-overlays'
  },
  {
    id: 'accessibility.captions-and-transcripts',
    category: 'accessibility',
    severity: 'required',
    title: 'Captions and transcripts',
    guidance:
      'Video needs synchronised captions, audio-only content needs a transcript, and visuals that carry meaning need audio description. Auto-captions alone are not enough.',
    url: 'https://specification.website/spec/accessibility/captions-and-transcripts'
  },
  {
    id: 'accessibility.data-tables',
    category: 'accessibility',
    severity: 'required',
    title: 'Accessible data tables',
    guidance:
      'Tabular data must use real <table> markup with a caption, header cells, and scope attributes so screen readers can announce row and column relationships.',
    url: 'https://specification.website/spec/accessibility/data-tables'
  },
  {
    id: 'accessibility.touch-target-size',
    category: 'accessibility',
    severity: 'required',
    title: 'Touch target size',
    guidance:
      'Interactive controls must be large enough to tap or click reliably. WCAG 2.2 sets a 24×24 CSS px minimum, with 44×44 CSS px as the enhanced target.',
    url: 'https://specification.website/spec/accessibility/touch-target-size'
  },
  {
    id: 'accessibility.hidden-until-found',
    category: 'accessibility',
    severity: 'recommended',
    title: 'Hidden until found',
    guidance:
      'Use hidden="until-found" for collapsible content so that browser find-in-page, assistive tech, and search engines can still reach the text and auto-expand it.',
    url: 'https://specification.website/spec/accessibility/hidden-until-found'
  },
  {
    id: 'accessibility.mobile-form-inputs',
    category: 'accessibility',
    severity: 'recommended',
    title: 'Mobile-friendly form inputs',
    guidance:
      "On a phone, the right input type, inputmode, and enterkeyhint summon the correct on-screen keyboard and a useful Enter key. Keep input text at 16px or larger so iOS Safari doesn't zoom on focus.",
    url: 'https://specification.website/spec/accessibility/mobile-form-inputs'
  },
  {
    id: 'accessibility.native-interactive-elements',
    category: 'accessibility',
    severity: 'recommended',
    title: 'Native interactive elements',
    guidance:
      'Prefer native HTML interactive elements — <button>, <a>, <details>/<summary>, <dialog> — over divs with click handlers. You get keyboard support, focus management, and assistive-tech semantics for free.',
    url: 'https://specification.website/spec/accessibility/native-interactive-elements'
  },
  {
    id: 'accessibility.css-state-selectors',
    category: 'accessibility',
    severity: 'recommended',
    title: 'CSS state and relational selectors',
    guidance:
      'Use `:has()` together with `:user-invalid`, `:user-valid`, `:placeholder-shown` and `:focus-within` to express form and component state in CSS, removing the JavaScript class-toggling pattern and the race conditions it brings.',
    url: 'https://specification.website/spec/accessibility/css-state-selectors'
  },
  // Security
  {
    id: 'security.https',
    category: 'security',
    severity: 'required',
    title: 'HTTPS and TLS',
    guidance:
      'Serve every page over HTTPS using TLS 1.2 or 1.3, redirect plain HTTP to HTTPS, and disable obsolete SSL and early TLS versions on every host you control.',
    url: 'https://specification.website/spec/security/https-tls',
    liveProbe: true
  },
  {
    id: 'security.hsts',
    category: 'security',
    severity: 'required',
    title: 'HSTS (Strict-Transport-Security)',
    guidance:
      'HSTS tells browsers to use HTTPS for your domain only, for a long time. Add max-age, includeSubDomains, and preload — but understand it is an irreversible commitment.',
    url: 'https://specification.website/spec/security/hsts',
    liveProbe: true
  },
  {
    id: 'security.mixed-content',
    category: 'security',
    severity: 'recommended',
    title: 'Mixed content and upgrade-insecure-requests',
    guidance:
      'An HTTPS page that loads any subresource over HTTP is mixed content. Serve every subresource over HTTPS, and send the upgrade-insecure-requests CSP directive as a safety net.',
    url: 'https://specification.website/spec/security/mixed-content'
  },
  {
    id: 'security.csp',
    category: 'security',
    severity: 'recommended',
    title: 'Content Security Policy (CSP)',
    guidance:
      'A CSP tells browsers which sources of script, style, image, and frame content to trust. A good policy stops most XSS and data-exfiltration attacks dead.',
    url: 'https://specification.website/spec/security/content-security-policy',
    liveProbe: true
  },
  {
    id: 'security.reporting-endpoints',
    category: 'security',
    severity: 'recommended',
    title: 'Reporting API (Reporting-Endpoints)',
    guidance:
      'A response header that names HTTP endpoints to which the browser POSTs structured violation reports — CSP and COOP breaches, permissions-policy violations, deprecations, interventions, and crashes — so you learn what is breaking in the field.',
    url: 'https://specification.website/spec/security/reporting-endpoints'
  },
  {
    id: 'security.content-type-options',
    category: 'security',
    severity: 'required',
    title: 'X-Content-Type-Options: nosniff',
    guidance:
      "The nosniff header stops browsers from guessing a response's content type. It blocks a class of attacks where a benign-looking file is interpreted as script or stylesheet.",
    url: 'https://specification.website/spec/security/x-content-type-options',
    liveProbe: true
  },
  {
    id: 'security.frame-ancestors',
    category: 'security',
    severity: 'required',
    title: 'Clickjacking protection (frame-ancestors / X-Frame-Options)',
    guidance:
      'Tell browsers who is allowed to embed your pages in an iframe. Use CSP frame-ancestors. X-Frame-Options is the legacy fallback.',
    url: 'https://specification.website/spec/security/frame-ancestors'
  },
  {
    id: 'security.cross-origin-isolation',
    category: 'security',
    severity: 'recommended',
    title: 'Cross-origin isolation (COOP / COEP / CORP)',
    guidance:
      'Three response headers — Cross-Origin-Opener-Policy, Cross-Origin-Embedder-Policy, and Cross-Origin-Resource-Policy — that sever risky cross-window and cross-origin links and defend against side-channel leaks.',
    url: 'https://specification.website/spec/security/cross-origin-isolation'
  },
  {
    id: 'security.referrer-policy',
    category: 'security',
    severity: 'recommended',
    title: 'Referrer-Policy',
    guidance:
      'Referrer-Policy controls how much URL information your site leaks when users follow a link or load a subresource. strict-origin-when-cross-origin is the sensible default.',
    url: 'https://specification.website/spec/security/referrer-policy'
  },
  {
    id: 'security.permissions-policy',
    category: 'security',
    severity: 'recommended',
    title: 'Permissions-Policy',
    guidance:
      'Permissions-Policy lets you turn off powerful browser features — camera, microphone, geolocation, payment, USB — for your own pages and for any iframes you embed.',
    url: 'https://specification.website/spec/security/permissions-policy'
  },
  {
    id: 'security.subresource-integrity',
    category: 'security',
    severity: 'recommended',
    title: 'Subresource Integrity (SRI)',
    guidance:
      'SRI adds a cryptographic hash to every third-party script and stylesheet so the browser refuses to run modified files. Essential for any external JS or CSS you depend on.',
    url: 'https://specification.website/spec/security/subresource-integrity'
  },
  {
    id: 'security.trusted-types',
    category: 'security',
    severity: 'recommended',
    title: 'Trusted Types',
    guidance:
      'Trusted Types make the browser reject plain strings at DOM injection sinks like innerHTML, demanding a vetted typed value instead. Switched on with two CSP directives, it neutralises a whole class of DOM-based XSS.',
    url: 'https://specification.website/spec/security/trusted-types'
  },
  {
    id: 'security.cookie-attributes',
    category: 'security',
    severity: 'required',
    title: 'Cookie attributes — Secure, HttpOnly, SameSite',
    guidance:
      'Every cookie should be Secure, HttpOnly where possible, and have an explicit SameSite. Use __Host- and __Secure- prefixes for session cookies.',
    url: 'https://specification.website/spec/security/cookie-attributes'
  },
  {
    id: 'security.clear-site-data',
    category: 'security',
    severity: 'optional',
    title: 'Clear-Site-Data',
    guidance:
      'Clear-Site-Data lets a response tell the browser to wipe cookies, storage, and caches for your origin. Send it on logout so a shared device keeps nothing behind.',
    url: 'https://specification.website/spec/security/clear-site-data'
  },
  {
    id: 'security.caa-records',
    category: 'security',
    severity: 'recommended',
    title: 'DNS CAA records',
    guidance:
      'A CAA record tells certificate authorities which of them are allowed to issue certificates for your domain. Cheap to add, blocks a class of mis-issuance attacks.',
    url: 'https://specification.website/spec/security/caa-records'
  },
  {
    id: 'security.dnssec',
    category: 'security',
    severity: 'optional',
    title: 'DNSSEC',
    guidance:
      'DNSSEC cryptographically signs DNS records so resolvers can verify they have not been tampered with. Strong defence in depth, but only with full registrar and registry support.',
    url: 'https://specification.website/spec/security/dnssec'
  },
  // Well-Known URIs
  {
    id: 'well-known.security-txt',
    category: 'well-known',
    severity: 'recommended',
    title: '/.well-known/security.txt',
    guidance:
      'A standard text file at /.well-known/security.txt tells security researchers how to report vulnerabilities. It is cheap to publish and dramatically lowers the bar for responsible disclosure.',
    url: 'https://specification.website/spec/security/security-txt'
  },
  {
    id: 'well-known.well-known-overview',
    category: 'well-known',
    severity: 'recommended',
    title: 'Well-known URIs',
    guidance:
      'The /.well-known/ path prefix is a standardised place to publish site-level metadata. RFC 8615 defines it; IANA keeps the registry of allowed names.',
    url: 'https://specification.website/spec/well-known/well-known-overview'
  },
  {
    id: 'well-known.change-password',
    category: 'well-known',
    severity: 'optional',
    title: '/.well-known/change-password',
    guidance:
      'A standard redirect endpoint that points password managers and users at your real change-password page. Only applicable if the site has user accounts — sites without logins have nothing to point at and should not implement it.',
    url: 'https://specification.website/spec/well-known/change-password'
  },
  {
    id: 'well-known.webauthn',
    category: 'well-known',
    severity: 'optional',
    title: '/.well-known/webauthn',
    guidance:
      'A JSON document at /.well-known/webauthn lists the origins allowed to use passkeys scoped to a single Relying Party ID. It enables WebAuthn Related Origin Requests — one passkey shared across several domains you own. Only applicable if the site uses passkeys across more than one origin.',
    url: 'https://specification.website/spec/well-known/webauthn'
  },
  {
    id: 'well-known.openid-configuration',
    category: 'well-known',
    severity: 'optional',
    title: '/.well-known/openid-configuration',
    guidance:
      "A JSON discovery document that describes an OpenID Connect provider's endpoints and capabilities. Only required if you are an OIDC identity provider.",
    url: 'https://specification.website/spec/well-known/openid-configuration'
  },
  {
    id: 'well-known.api-catalog',
    category: 'well-known',
    severity: 'recommended',
    title: '/.well-known/api-catalog',
    guidance:
      'RFC 9727 publishes a machine-readable index of the APIs and resources a host exposes. Served as a Linkset (RFC 9264) JSON document, discoverable via the api-catalog link relation.',
    url: 'https://specification.website/spec/well-known/api-catalog'
  },
  {
    id: 'well-known.webfinger',
    category: 'well-known',
    severity: 'optional',
    title: '/.well-known/webfinger',
    guidance:
      'WebFinger (RFC 7033) resolves an account identifier such as acct:user@example.com to a set of links. The Fediverse uses it to discover ActivityPub actors.',
    url: 'https://specification.website/spec/well-known/webfinger'
  },
  {
    id: 'well-known.apple-app-site-association',
    category: 'well-known',
    severity: 'optional',
    title: '/.well-known/apple-app-site-association',
    guidance:
      'A JSON file that tells iOS, iPadOS and macOS which Apple apps may handle which URLs on your domain. Required for Universal Links and several other Apple features.',
    url: 'https://specification.website/spec/well-known/apple-app-site-association'
  },
  {
    id: 'well-known.assetlinks-json',
    category: 'well-known',
    severity: 'optional',
    title: '/.well-known/assetlinks.json',
    guidance:
      "Android's Digital Asset Links file proves that an Android app and a web domain are owned by the same entity. It powers App Links and Smart Lock for Passwords.",
    url: 'https://specification.website/spec/well-known/assetlinks-json'
  },
  {
    id: 'well-known.nodeinfo',
    category: 'well-known',
    severity: 'optional',
    title: '/.well-known/nodeinfo',
    guidance:
      'A discovery URI for federated platforms. It returns links to NodeInfo documents that describe the software, version and basic statistics of a server.',
    url: 'https://specification.website/spec/well-known/nodeinfo'
  },
  {
    id: 'well-known.traffic-advice',
    category: 'well-known',
    severity: 'optional',
    title: '/.well-known/traffic-advice',
    guidance:
      "A JSON file that tells private prefetch proxies — most notably Chrome's — whether to send prefetch traffic to your origin, and at what fraction. Optional opt-out / throttle mechanism, provisionally registered with IANA.",
    url: 'https://specification.website/spec/well-known/traffic-advice'
  },
  // Agent Readiness
  {
    id: 'agent-readiness.agent-readiness-overview',
    category: 'agent-readiness',
    severity: 'recommended',
    title: 'Agent readiness',
    guidance:
      'Agent readiness is the set of choices that make a site legible to AI agents and LLMs: stable URLs, structured data, clean semantics, robots controls, and machine-readable endpoints.',
    url: 'https://specification.website/spec/agent-readiness/agent-readiness-overview'
  },
  {
    id: 'agent-readiness.llms-txt',
    category: 'agent-readiness',
    severity: 'recommended',
    title: '/llms.txt',
    guidance:
      'A proposed markdown file at the site root that gives LLMs a curated index of your most important content. Emerging convention, not a ratified standard.',
    url: 'https://specification.website/spec/agent-readiness/llms-txt'
  },
  {
    id: 'agent-readiness.llms-full-txt',
    category: 'agent-readiness',
    severity: 'optional',
    title: '/llms-full.txt',
    guidance:
      'An extended companion to /llms.txt that concatenates the full markdown content of your key pages into a single file. Useful for small sites, costly for large ones.',
    url: 'https://specification.website/spec/agent-readiness/llms-full-txt'
  },
  {
    id: 'agent-readiness.markdown',
    category: 'agent-readiness',
    severity: 'recommended',
    title: 'Per-page Markdown source endpoints',
    guidance:
      "Expose every documentation page's raw Markdown source at a predictable URL — via a .md suffix on the canonical URL, content negotiation, or both. Agents pull source instead of parsing HTML.",
    url: 'https://specification.website/spec/agent-readiness/markdown-source-endpoints'
  },
  {
    id: 'agent-readiness.robots-for-ai-crawlers',
    category: 'agent-readiness',
    severity: 'recommended',
    title: 'robots.txt for AI crawlers',
    guidance:
      'Major AI vendors publish named user-agents for their crawlers. Setting an explicit allow or disallow per agent is the clearest way to control how your content is used.',
    url: 'https://specification.website/spec/agent-readiness/robots-for-ai-crawlers'
  },
  {
    id: 'agent-readiness.content-signals',
    category: 'agent-readiness',
    severity: 'optional',
    title: 'Content Signals in robots.txt',
    guidance:
      'Add Content-Signal directives to robots.txt to declare whether AI crawlers may search, ingest, or train on your content. An emerging IETF AI Preferences / IAB Tech Lab proposal that some validators already check.',
    url: 'https://specification.website/spec/agent-readiness/content-signals'
  },
  {
    id: 'agent-readiness.web-bot-auth',
    category: 'agent-readiness',
    severity: 'optional',
    title: 'Web Bot Auth — verifiable bot identity',
    guidance:
      'Web Bot Auth lets a bot prove who it is by signing each HTTP request with a key it controls. Sites can then allow or block specific bots without IP allow-lists, user-agent strings, or guesswork. Built on RFC 9421 HTTP Message Signatures.',
    url: 'https://specification.website/spec/agent-readiness/web-bot-auth'
  },
  {
    id: 'agent-readiness.stable-urls',
    category: 'agent-readiness',
    severity: 'required',
    title: 'Stable URLs',
    guidance:
      'URLs are public contracts. Once published, they should keep working. Breaking them invalidates citations, bookmarks, links, and agent caches — and is almost always avoidable.',
    url: 'https://specification.website/spec/agent-readiness/stable-urls'
  },
  {
    id: 'agent-readiness.structured-data-for-agents',
    category: 'agent-readiness',
    severity: 'recommended',
    title: 'Structured data for agents',
    guidance:
      'JSON-LD with schema.org types gives agents typed facts about your page. It is the same markup search engines use, and agents lean on it just as heavily.',
    url: 'https://specification.website/spec/agent-readiness/structured-data-for-agents'
  },
  {
    id: 'agent-readiness.machine-readable-formats',
    category: 'agent-readiness',
    severity: 'recommended',
    title: 'Machine-readable formats',
    guidance:
      'Offer JSON, RSS, or plain markdown endpoints alongside HTML where it makes sense. Agents and feed readers prefer typed data over scraped HTML.',
    url: 'https://specification.website/spec/agent-readiness/machine-readable-formats'
  },
  {
    id: 'agent-readiness.link-headers',
    category: 'agent-readiness',
    severity: 'recommended',
    title: 'HTTP Link headers for discovery',
    guidance:
      'Use the HTTP Link header to advertise machine-readable resources — llms.txt, sitemap, api-catalog, RSS — directly in the response. Agents that never parse your HTML can still find what they need.',
    url: 'https://specification.website/spec/agent-readiness/link-headers'
  },
  {
    id: 'agent-readiness.mcp-and-tool-discovery',
    category: 'agent-readiness',
    severity: 'optional',
    title: 'MCP and tool discovery',
    guidance:
      'The Model Context Protocol is an emerging way for sites to expose queryable tools to agents over JSON-RPC. Relevant whenever your content has structure worth filtering — even for a static reference site like this one.',
    url: 'https://specification.website/spec/agent-readiness/mcp-and-tool-discovery'
  },
  {
    id: 'agent-readiness.a2a-agent-cards',
    category: 'agent-readiness',
    severity: 'optional',
    title: 'A2A agent cards',
    guidance:
      'The Agent-to-Agent (A2A) protocol lets an autonomous agent find another autonomous agent and call it over JSON-RPC. Discovery hinges on a single well-known file: `/.well-known/agent-card.json`. Relevant whenever your service exposes agentic behaviour another agent might want to delegate to.',
    url: 'https://specification.website/spec/agent-readiness/a2a-agent-cards'
  },
  {
    id: 'agent-readiness.agent-skills-discovery',
    category: 'agent-readiness',
    severity: 'recommended',
    title: 'Agent Skills discovery',
    guidance:
      'A well-known URI that lists Agent Skills — short, scoped instructions an AI agent can load to work better with your site. Emerging convention via a Cloudflare-led RFC; still draft, still cheap to ship.',
    url: 'https://specification.website/spec/agent-readiness/agent-skills-discovery'
  },
  {
    id: 'agent-readiness.dns-aid',
    category: 'agent-readiness',
    severity: 'optional',
    title: 'DNS for AI Discovery (DNS-AID)',
    guidance:
      'Publish SVCB/HTTPS records under _agents.example.com so agents can discover your services from DNS, before any HTTP round-trip. Pair with DNSSEC so the answer is authenticated.',
    url: 'https://specification.website/spec/agent-readiness/dns-aid'
  },
  {
    id: 'agent-readiness.agentic-resource-discovery',
    category: 'agent-readiness',
    severity: 'optional',
    title: 'Agentic Resource Discovery (ARD)',
    guidance:
      'Publish an AI Catalog at /.well-known/ai-catalog.json listing the agent capabilities your domain offers — MCP servers, A2A agents — so registries and agents can find and trust them from one fetch.',
    url: 'https://specification.website/spec/agent-readiness/agentic-resource-discovery'
  },
  {
    id: 'agent-readiness.nlweb',
    category: 'agent-readiness',
    severity: 'optional',
    title: 'NLWeb — conversational interface discovery',
    guidance:
      'NLWeb is an emerging convention for exposing a site as a conversational AI endpoint. A site advertises an `/ask`-style endpoint via a `rel="nlweb"` link and serves an MCP-compatible JSON-RPC interface that agents can query in natural language.',
    url: 'https://specification.website/spec/agent-readiness/nlweb'
  },
  {
    id: 'agent-readiness.webmcp',
    category: 'agent-readiness',
    severity: 'optional',
    title: 'WebMCP — browser-native tools for agents',
    guidance:
      'WebMCP lets a page register tools that an in-browser AI agent can call directly, using a `navigator.modelContext` JavaScript API. It turns a site into an agent surface without server-side MCP plumbing.',
    url: 'https://specification.website/spec/agent-readiness/webmcp'
  },
  {
    id: 'agent-readiness.okf-bundle',
    category: 'agent-readiness',
    severity: 'optional',
    title: 'Open Knowledge Format (OKF) bundle',
    guidance:
      'Publish your whole knowledge base as an Open Knowledge Format bundle — a tree of Markdown concept files with typed front matter — so an agent can ingest the entire corpus in one fetch instead of scraping page by page.',
    url: 'https://specification.website/spec/agent-readiness/okf-bundle'
  },
  {
    id: 'agent-readiness.schemamap',
    category: 'agent-readiness',
    severity: 'optional',
    title: 'Schemamap — discoverable JSON-LD endpoints per resource',
    guidance:
      'A convention this site proposes — no external standard exists yet. `/schemamap.xml` indexes one JSON-LD endpoint per resource so agents fetch the structured-data graph directly instead of extracting it from HTML.',
    url: 'https://specification.website/spec/agent-readiness/schemamap'
  },
  // Performance
  {
    id: 'performance.core-web-vitals',
    category: 'performance',
    severity: 'required',
    title: 'Core Web Vitals (LCP, INP, CLS)',
    guidance:
      'Core Web Vitals measure loading, responsiveness, and visual stability. Hit LCP ≤ 2.5s, INP ≤ 200ms, and CLS ≤ 0.1 at the 75th percentile of real users.',
    url: 'https://specification.website/spec/performance/core-web-vitals'
  },
  {
    id: 'performance.image-optimization',
    category: 'performance',
    severity: 'required',
    title: 'Image optimisation',
    guidance:
      'Serve images in modern formats (WebP, AVIF), at the right size for the viewport, with explicit dimensions. Images are the largest payload on most pages.',
    url: 'https://specification.website/spec/performance/image-optimization'
  },
  {
    id: 'performance.lazy-loading',
    category: 'performance',
    severity: 'recommended',
    title: 'Lazy loading images, iframes, and video',
    guidance:
      'Native lazy loading defers off-screen images, iframes, and (recently) video until the user scrolls near them. Use loading="lazy" — but never on the LCP element.',
    url: 'https://specification.website/spec/performance/lazy-loading'
  },
  {
    id: 'performance.preload-prefetch-preconnect',
    category: 'performance',
    severity: 'recommended',
    title: 'Preload, prefetch, preconnect',
    guidance:
      'Resource hints let you tell the browser what is coming. Preload the LCP image and critical fonts, preconnect to third-party origins, prefetch the next navigation.',
    url: 'https://specification.website/spec/performance/preload-prefetch-preconnect'
  },
  {
    id: 'performance.early-hints',
    category: 'performance',
    severity: 'optional',
    title: '103 Early Hints',
    guidance:
      'An informational HTTP response that carries Link headers — preload, preconnect — to the browser before the final response is ready, putting server think-time to work.',
    url: 'https://specification.website/spec/performance/early-hints'
  },
  {
    id: 'performance.cache-control',
    category: 'performance',
    severity: 'required',
    title: 'Cache-Control headers',
    guidance:
      'Cache-Control tells browsers and CDNs how long to keep a response. Use immutable + max-age=31536000 for fingerprinted assets and short or no-cache for HTML.',
    url: 'https://specification.website/spec/performance/cache-control'
  },
  {
    id: 'performance.conditional-requests',
    category: 'performance',
    severity: 'recommended',
    title: 'Conditional requests (ETag, Last-Modified, 304)',
    guidance:
      'Send a validator — ETag or Last-Modified — on every cacheable response, and honour If-None-Match / If-Modified-Since so unchanged resources return an empty 304 instead of the full body.',
    url: 'https://specification.website/spec/performance/conditional-requests'
  },
  {
    id: 'performance.no-vary-search',
    category: 'performance',
    severity: 'recommended',
    title: 'No-Vary-Search response header',
    guidance:
      'The `No-Vary-Search` response header tells browsers and caches that some URL query parameters (tracking, UTM, sort order) do not change the response. The cached entry for the canonical URL is reused for variants — fewer fetches, better prefetch hits, less duplicate work.',
    url: 'https://specification.website/spec/performance/no-vary-search'
  },
  {
    id: 'performance.compression',
    category: 'performance',
    severity: 'required',
    title: 'Compression (gzip, brotli, zstd)',
    guidance:
      "Compress text responses with brotli where supported, gzip everywhere else. zstd is emerging. Don't compress already-compressed media.",
    url: 'https://specification.website/spec/performance/compression'
  },
  {
    id: 'performance.font-loading',
    category: 'performance',
    severity: 'recommended',
    title: 'Web font loading',
    guidance:
      'Self-host WOFF2 fonts, subset them, set font-display: swap so text is readable while the font loads, and preload the critical face only when it styles above-the-fold content.',
    url: 'https://specification.website/spec/performance/font-loading'
  },
  {
    id: 'performance.critical-css',
    category: 'performance',
    severity: 'recommended',
    title: 'Critical CSS and render-blocking resources',
    guidance:
      'Inline the CSS needed for above-the-fold content and defer the rest. Render-blocking resources in <head> are the single biggest cause of slow first paint.',
    url: 'https://specification.website/spec/performance/critical-css'
  },
  {
    id: 'performance.script-loading',
    category: 'performance',
    severity: 'recommended',
    title: 'Script loading — defer, async, module',
    guidance:
      'Choose the right script-loading attribute for every <script>: defer for app code, async for independent third-party, type=module for modern code. Bare <script> in <head> is always wrong.',
    url: 'https://specification.website/spec/performance/script-loading'
  },
  {
    id: 'performance.http3',
    category: 'performance',
    severity: 'recommended',
    title: 'HTTP/2 and HTTP/3',
    guidance:
      'Serve over HTTP/2 at minimum and HTTP/3 where you can. Multiplexing eliminates head-of-line blocking; QUIC removes TCP handshake delays.',
    url: 'https://specification.website/spec/performance/http3'
  },
  {
    id: 'performance.http1-workarounds',
    category: 'performance',
    severity: 'avoid',
    title: 'HTTP/1.1 workarounds: sharding, sprites, and bundling',
    guidance:
      "Domain sharding and image sprites were workarounds for HTTP/1.1's connection limit; under HTTP/2 and HTTP/3 they hurt — drop them. Bundling is the nuanced one: stop concatenating to cut requests, start doing it to cut bytes.",
    url: 'https://specification.website/spec/performance/http1-workarounds'
  },
  {
    id: 'performance.speculation-rules',
    category: 'performance',
    severity: 'recommended',
    title: 'Speculation Rules',
    guidance:
      'Tell the browser which links to prefetch or prerender before the user clicks. Done well, navigations feel instant; done carelessly, you burn bandwidth on pages nobody visits.',
    url: 'https://specification.website/spec/performance/speculation-rules'
  },
  {
    id: 'performance.resource-hints',
    category: 'performance',
    severity: 'recommended',
    title: 'Resource hints overview',
    guidance:
      'Five resource hints — dns-prefetch, preconnect, preload, modulepreload, prefetch — cover every stage of the request lifecycle. Pick the right one for the job.',
    url: 'https://specification.website/spec/performance/resource-hints'
  },
  {
    id: 'performance.view-transitions',
    category: 'performance',
    severity: 'recommended',
    title: 'View Transitions',
    guidance:
      'Animate between states (same-document) or between pages (cross-document) with a single CSS opt-in. Replaces ad-hoc SPA animation libraries with a platform primitive.',
    url: 'https://specification.website/spec/performance/view-transitions'
  },
  {
    id: 'performance.bfcache',
    category: 'performance',
    severity: 'recommended',
    title: 'Back/forward cache (BFCache)',
    guidance:
      'Keep pages BFCache-eligible so back/forward navigation restores them instantly from memory, with no reload, no hydration, and no repaint.',
    url: 'https://specification.website/spec/performance/bfcache'
  },
  {
    id: 'performance.visibility-aware-rendering',
    category: 'performance',
    severity: 'recommended',
    title: 'Visibility-aware rendering',
    guidance:
      'Use `content-visibility` with `contain-intrinsic-size` to skip layout and paint for off-screen content, and Intersection Observer to drive lazy behaviour, instead of scroll and resize listeners.',
    url: 'https://specification.website/spec/performance/visibility-aware-rendering'
  },
  {
    id: 'performance.css-containment',
    category: 'performance',
    severity: 'optional',
    title: 'CSS containment',
    guidance:
      "Use `contain: layout paint style` (or the `contain: content` shorthand) to tell the browser that an element's internals cannot affect the rest of the page, so reflow and repaint stay isolated to that subtree.",
    url: 'https://specification.website/spec/performance/css-containment'
  },
  {
    id: 'performance.scroll-driven-animations',
    category: 'performance',
    severity: 'optional',
    title: 'Scroll-driven animations',
    guidance:
      'Drive CSS animations from scroll position or element visibility with `scroll-timeline` and `view-timeline`, replacing JS scroll-listener libraries with compositor-thread animation.',
    url: 'https://specification.website/spec/performance/scroll-driven-animations'
  },
  {
    id: 'performance.scrollbar-gutter',
    category: 'performance',
    severity: 'recommended',
    title: 'Scrollbar gutter',
    guidance:
      "Use scrollbar-gutter: stable to reserve scrollbar space and stop horizontal layout shift between pages or states that overflow vs. don't.",
    url: 'https://specification.website/spec/performance/scrollbar-gutter'
  },
  {
    id: 'performance.dynamic-viewport-units',
    category: 'performance',
    severity: 'recommended',
    title: 'Dynamic viewport units (dvh, svh, lvh)',
    guidance:
      "On mobile, 100vh is taller than the screen because it ignores the browser's collapsing toolbar. Use dvh, svh, and lvh to size full-height elements to the viewport that is actually visible.",
    url: 'https://specification.website/spec/performance/dynamic-viewport-units'
  },
  {
    id: 'performance.compression-dictionary-transport',
    category: 'performance',
    severity: 'optional',
    title: 'Compression Dictionary Transport',
    guidance:
      'Use a previously served response, or a dedicated dictionary, as a Brotli/Zstandard dictionary so updated assets compress to a fraction of their size. Pure progressive enhancement over ordinary compression.',
    url: 'https://specification.website/spec/performance/compression-dictionary-transport'
  },
  {
    id: 'performance.server-timing',
    category: 'performance',
    severity: 'optional',
    title: 'Server-Timing header',
    guidance:
      'Server-Timing surfaces backend metrics — database time, cache hits, edge processing — in browser DevTools and to RUM via the PerformanceServerTiming API. Send it when you measure server-side latency, and keep the values free of sensitive infrastructure detail.',
    url: 'https://specification.website/spec/performance/server-timing'
  },
  // Privacy
  {
    id: 'privacy.policy',
    category: 'privacy',
    severity: 'required',
    title: 'Privacy policy',
    guidance:
      'A privacy policy tells visitors what personal data you collect, why, on what legal basis, who you share it with, how long you keep it, and what rights they have.',
    url: 'https://specification.website/spec/privacy/privacy-policy'
  },
  {
    id: 'privacy.cookie-consent',
    category: 'privacy',
    severity: 'required',
    title: 'Cookie consent',
    guidance:
      'In the EU and UK, non-essential cookies and similar storage require freely given, informed, specific, and unambiguous opt-in consent before they are set.',
    url: 'https://specification.website/spec/privacy/cookie-consent'
  },
  {
    id: 'privacy.global-privacy-control',
    category: 'privacy',
    severity: 'recommended',
    title: 'Global Privacy Control (GPC)',
    guidance:
      'Global Privacy Control is a browser-level signal that tells websites the user opts out of the sale or sharing of their personal data. California and Colorado require sites to honour it.',
    url: 'https://specification.website/spec/privacy/global-privacy-control'
  },
  {
    id: 'privacy.third-party-scripts',
    category: 'privacy',
    severity: 'recommended',
    title: 'Third-party scripts and privacy',
    guidance:
      'Every script loaded from another domain can read cookies, see the URL, and exfiltrate data from your page. Audit them, justify them, and lock them down.',
    url: 'https://specification.website/spec/privacy/third-party-scripts'
  },
  {
    id: 'privacy.analytics-privacy',
    category: 'privacy',
    severity: 'recommended',
    title: 'Privacy-respecting analytics',
    guidance:
      'You can measure traffic without surveilling visitors. Aggregate, cookieless, EU-hosted analytics tools answer most product questions without the consent and transfer problems of ad-tech analytics.',
    url: 'https://specification.website/spec/privacy/analytics-privacy'
  },
  {
    id: 'privacy.data-minimization',
    category: 'privacy',
    severity: 'recommended',
    title: 'Data minimisation',
    guidance:
      'Collect only the personal data you actually need for a specific purpose, keep it only as long as you need it, and redact it from anywhere it leaks unnecessarily.',
    url: 'https://specification.website/spec/privacy/data-minimization'
  },
  // Resilience
  {
    id: 'resilience.custom-404',
    category: 'resilience',
    severity: 'required',
    title: 'Custom error pages (404, 500)',
    guidance:
      'Custom error pages must return the correct HTTP status code, explain what went wrong in plain language, and offer the user a way forward without leaking implementation details.',
    url: 'https://specification.website/spec/resilience/error-pages'
  },
  {
    id: 'resilience.maintenance-pages',
    category: 'resilience',
    severity: 'recommended',
    title: 'Maintenance pages and 503',
    guidance:
      'When the site is intentionally offline, return HTTP 503 with a Retry-After header and a page that tells users what is happening and when to come back.',
    url: 'https://specification.website/spec/resilience/maintenance-pages'
  },
  {
    id: 'resilience.graceful-degradation',
    category: 'resilience',
    severity: 'recommended',
    title: 'Graceful degradation when JavaScript fails',
    guidance:
      'Core content and primary navigation should keep working when JavaScript fails to load or throws — treat client-side scripts as an enhancement, not the delivery mechanism.',
    url: 'https://specification.website/spec/resilience/graceful-degradation'
  },
  {
    id: 'resilience.offline-support',
    category: 'resilience',
    severity: 'optional',
    title: 'Offline support and service workers',
    guidance:
      'A service worker can serve a cached offline fallback page when the network fails, keeping the site usable on flaky connections and turning hard failures into graceful ones.',
    url: 'https://specification.website/spec/resilience/offline-support'
  },
  {
    id: 'resilience.pwa-manifest',
    category: 'resilience',
    severity: 'recommended',
    title: 'Web app manifest',
    guidance:
      'A web app manifest is a small JSON file that tells browsers how the site should appear when installed — its name, icons, start URL, theme colour, and display mode.',
    url: 'https://specification.website/spec/resilience/pwa-manifest'
  },
  {
    id: 'resilience.monitoring-uptime',
    category: 'resilience',
    severity: 'recommended',
    title: 'Monitoring and uptime',
    guidance:
      'Monitor the site from outside your own infrastructure, combine synthetic checks with real user data, and run a status page on a separate host so it stays up when the site does not.',
    url: 'https://specification.website/spec/resilience/monitoring-uptime'
  },
  // Internationalisation
  {
    id: 'i18n.international-url-structure',
    category: 'i18n',
    severity: 'recommended',
    title: 'International URL structure',
    guidance:
      'Pick a single URL pattern for multilingual or multi-regional content — country-code top-level domain, subdomain, or subdirectory — and stick with it. Optionally localise the slugs too.',
    url: 'https://specification.website/spec/i18n/international-url-structure'
  },
  {
    id: 'i18n.hreflang',
    category: 'i18n',
    severity: 'recommended',
    title: 'hreflang for language and regional URLs',
    guidance:
      'hreflang tells search engines which language or regional version of a page to show to which user. It uses BCP 47 codes and must be reciprocal across all alternates.',
    url: 'https://specification.website/spec/i18n/hreflang'
  },
  {
    id: 'i18n.localised-metadata',
    category: 'i18n',
    severity: 'recommended',
    title: 'Localised page metadata',
    guidance:
      'Translate every visible string in the head and in structured data — title, meta description, Open Graph fields, JSON-LD names and descriptions, image alt text — not just the body. A localised body with English metadata is a half-translation.',
    url: 'https://specification.website/spec/i18n/localised-metadata'
  },
  {
    id: 'i18n.sitemap-hreflang',
    category: 'i18n',
    severity: 'optional',
    title: 'hreflang in XML sitemaps',
    guidance:
      'Declare language and regional alternates inside the XML sitemap with xhtml:link instead of in the HTML head. Easier to maintain at scale and keeps localisation metadata separate from content.',
    url: 'https://specification.website/spec/i18n/sitemap-hreflang'
  },
  {
    id: 'i18n.avoid-auto-geo-redirects',
    category: 'i18n',
    severity: 'avoid',
    title: 'Avoid automatic IP-based language redirects',
    guidance:
      'Automatically redirecting visitors to a locale based on IP geolocation or Accept-Language is an anti-pattern. It traps users in the wrong language, breaks search crawlers, and breaks shared links. Let users choose.',
    url: 'https://specification.website/spec/i18n/avoid-auto-geo-redirects'
  },
  {
    id: 'i18n.lang-attribute',
    category: 'i18n',
    severity: 'required',
    title: 'lang attribute on inline content',
    guidance:
      'Mark passages, phrases, and inline elements that differ from the document language with a lang attribute. WCAG 3.1.2 requires it so assistive tech can switch pronunciation.',
    url: 'https://specification.website/spec/i18n/lang-attribute'
  },
  {
    id: 'i18n.translate-attribute',
    category: 'i18n',
    severity: 'optional',
    title: 'translate attribute for untranslatable content',
    guidance:
      'The translate attribute marks content that automatic translation systems must leave alone — brand names, code, and identifiers. Use translate="no" so Google Translate and the browser\'s built-in translation don\'t mangle terms that have no localised form.',
    url: 'https://specification.website/spec/i18n/translate-attribute'
  },
  {
    id: 'i18n.language-switcher',
    category: 'i18n',
    severity: 'recommended',
    title: 'Language switcher',
    guidance:
      "List each locale in its own language ('Deutsch', '日本語', 'العربية') and mark it with the right lang attribute. Don't use flags — flags are countries, not languages.",
    url: 'https://specification.website/spec/i18n/language-switcher'
  },
  {
    id: 'i18n.rtl-support',
    category: 'i18n',
    severity: 'recommended',
    title: 'RTL and bidirectional text',
    guidance:
      'Sites that serve Arabic, Hebrew, Persian, or Urdu must set dir="rtl" and use CSS logical properties so layouts mirror correctly without hard-coded left and right.',
    url: 'https://specification.website/spec/i18n/rtl-support'
  },
  {
    id: 'i18n.writing-modes',
    category: 'i18n',
    severity: 'optional',
    title: 'Writing modes and CJK line breaking',
    guidance:
      'Vertical text (Japanese, Traditional Chinese, Mongolian) needs CSS writing-mode. Chinese, Japanese, Korean, and Thai also need explicit line-break and word-break rules so wrapping respects script-specific conventions.',
    url: 'https://specification.website/spec/i18n/writing-modes'
  },
  {
    id: 'i18n.locale-content',
    category: 'i18n',
    severity: 'recommended',
    title: 'Locale-aware content',
    guidance:
      "Dates, numbers, currency, and units should be formatted in the user's locale. Use Intl APIs in the browser and the same locale data server-side so output matches expectations.",
    url: 'https://specification.website/spec/i18n/locale-content'
  },
  {
    id: 'i18n.plural-rules',
    category: 'i18n',
    severity: 'recommended',
    title: 'Plural rules and grammatical number',
    guidance:
      "Most languages don't pluralise like English. Use CLDR plural categories — zero, one, two, few, many, other — via Intl.PluralRules instead of hard-coded 'item' vs 'items' logic.",
    url: 'https://specification.website/spec/i18n/plural-rules'
  },
  {
    id: 'i18n.idn-support',
    category: 'i18n',
    severity: 'optional',
    title: 'Internationalised Domain Names (IDN)',
    guidance:
      'IDNs let domain names contain non-ASCII characters. They are encoded as Punycode on the wire and rendered as Unicode in the browser, subject to anti-spoofing rules.',
    url: 'https://specification.website/spec/i18n/idn-support'
  },
  // --- Setu-specific (not in the spec checklist) ---
  {
    id: 'seo.homepage',
    category: 'seo',
    severity: 'required',
    title: 'Homepage resolves',
    guidance:
      "The homepage you've configured resolves to an existing content entry.",
    url: 'https://specification.website/spec/seo/url-structure',
    needsScan: true
  },
  {
    id: 'foundations.entry-title',
    category: 'foundations',
    severity: 'required',
    title: 'Entry titles',
    guidance: 'Every content entry has a non-empty title.',
    url: 'https://specification.website/spec/foundations/title',
    needsScan: true
  },
  {
    id: 'foundations.twitter-card',
    category: 'foundations',
    severity: 'optional',
    title: 'Twitter/X Card tags',
    guidance:
      'twitter: card tags refine link previews on X/Twitter (Open Graph covers most cases).',
    url: 'https://specification.website/spec/foundations/open-graph'
  }
]
